---
# Gitlab CI file

# docker image
image: google/cloud-sdk:alpine

# stages
stages:
  - lint
  - deploy
  - after

# lint Python code
#python lint:
#  stage: lint
#  image: python:3-alpine
#  script:
#    - apk add gcc git musl-dev
#    - pip install pylint
#    - git ls-files --exclude='*.py' --ignored | xargs pylint

# lint Dockerfiles
docker lint:
  stage: lint
  image: jonakoudijs/hadolint:latest
  script:
    - git ls-files --exclude='Dockerfile*' --ignored | xargs hadolint

# deploy api to app engine
deploy app:
  stage: deploy
  script:
    - gcloud auth activate-service-account --key-file=$GCLOUD_SERVICE_KEY
    - gcloud app deploy --project=steamcmd app.yaml --quiet
  only:
    - master

# download latest SteamCMD
connect api:
  stage: after
  script:
    - curl --connect-timeout 120 --max-time 120 https://api.steamcmd.net/1
  only:
    - master
