---
# Gitlab CI file

# docker image
image: python:3-alpine

# define DIND vars
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
services:
  - docker:dind

# stages
stages:
  - validate
  - deploy
  - after

# lint Dockerfiles
docker lint:
  stage: validate
  image: jonakoudijs/hadolint:latest
  script:
    - git ls-files --exclude='Dockerfile*' --ignored | xargs hadolint

# lint Python code
python lint:
  stage: validate
  script:
    - apk add gcc git musl-dev
    - pip install pylint
    - pip install -r requirements.txt
    - git ls-files --exclude='*.py' --ignored | xargs pylint --exit-zero

# test Python code
python test:
  stage: validate
  script:
    - apk add gcc git musl-dev
    - pip install pylint
    - pip install -r requirements.txt
    - git ls-files --exclude='*.py' --ignored | xargs pylint --errors-only

# deploy api to app engine
deploy app:
  stage: deploy
  image: docker:stable
  script:
    - apk add bash curl nodejs
    - curl https://cli-assets.heroku.com/install.sh | sh
    - heroku container:login
    - heroku container:push web --app steamcmd
    - heroku container:release web --app steamcmd
  only:
    - master

# download latest SteamCMD
warmup api:
  stage: after
  script:
    - apk add curl
    - curl --connect-timeout 120 --max-time 120 https://api.steamcmd.net/1
    - curl --connect-timeout 120 --max-time 120 https://api.steamcmd.net/1
  only:
    - master
