---
# Google Cloud App Engine deployment config

# define custom runtime
runtime: custom
env: flex

# set specifications to low (free tier)
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
