version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/data
    environment:
      PORT: 8080
      SENTRY: 0
      REDIS_URL: redis://redis:6379
      GUNICORN_CMD_ARGS: "--reload"
      PYTHONUNBUFFERED: "TRUE"
    restart: always
  redis:
    image: "redis:alpine"
